name: Get git comment action

description: GitHub actions to get git comment.

author: technote-space

inputs:
  SEPARATOR:
    description: Separator of multiline messages.
    default: ' '
    required: true
  FORMAT:
    description: Format of git log.
    default: '%B'
    required: true
  SET_ENV_NAME:
    description: Env name.
    default: COMMIT_MESSAGE
    required: false

outputs:
  message:
    description: git commit message

branding:
  icon: 'message-square'
  color: 'blue'

runs:
  using: node12
  main: lib/main.js
